// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  message: string;
  'name-of-animation': string;
  title: string;
  'title-animation': string;
}
export const cssExports: CssExports;
export default cssExports;
